// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enkmiehkaszodcdsmvao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVua21pZWhrYXN6b2RjZHNtdmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Nzc5NjUsImV4cCI6MjA1ODI1Mzk2NX0.HzsTzqYMBU4gQvII1ihxFeNB-gGzGw2LxanUUCK9UdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);